### ISSUE TITLE
(Postgrex.Error) ERROR (undefined_table): relation "users" does not exist

### ISSUE THREAD

**Issue by dogagithub** [gutschilla/phoenix-skeleton#3]
How to create these tables?

**Comment by gutschilla** [comment]
Did you run the migrations via

`mix ecto.migrate Repo`

? The migrations use phoenix' infrastructur and will create all necessary tables and an admin user with password "admin.

You may also simply execute the SQL by yourself. They sit in priv/repo/migrations but I highly recommend using the migration infrastructure.

**Comment by gutschilla** [comment]
And thanks a lot for your input! I will definitely update the README to point this out more clearly.

**Comment by gutschilla** [comment]
Updated README.md, hope this helps.

**Comment by Abhishek2511** [comment]
it worked. Thanks

**Comment by Nandha23311** [comment]
it works ,Thanks Very much
